apiVersion: v1
kind: Service
metadata:
  name: simple-app
  namespace: simple-app
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: external
spec:
  selector:
    app: simple-app
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
